display_name: Coalesce Demo
fields:
  badge: "{{ data.source | default('demo') }}"
  title: "{{ data.summary | default('Updated item with coalesce') }}"
  link: "{{ data.link | default('') }}"
  description: |
    {% if data.event_id %}
    Event ID: {{ data.event_id }}
    {% else %}
    Event ID not provided.
    {% endif %}
  coalesce: "{{ data.event_id | default('') }}"
