display_name: DIUN
fields:
  badge: "Update"
  title: "{{ image }} has been updated"
  link: "{{ hub_link }}"
  coalesce: "{{ metadata.ctn_name }}"
  description: |
    {{ metadata.ctn_name }} has been updated. New image: [**{{ image }}**]({{ hub_link }})
